name: Deploy to GitHub Pages

on:
  # 每次推送到 `main` 分支时触发
  push:
    branches: [ main ]
  # 允许你在 GitHub 仓库的 Actions 页面手动触发
  workflow_dispatch:

# 允许这个 job 克隆仓库并创建 page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        # 使用官方的 Astro Action
        uses: withastro/action@v3
        with:
          # Astro Action 会自动检测 pnpm-lock.yaml 并使用 pnpm
          # node-version: 20 # 可以指定 Node.js 版本，默认就是 20

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4